

import type { Metadata } from "next";
import "./globals.css";
import "flag-icons/css/flag-icons.min.css";
import Navbar from "@/components/functional/navbar";

import { GeistSans } from "geist/font/sans";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=''>
      <body
        className={`${GeistSans.variable}  bg-background font-sans`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
